#!/bin/bash
# Keep the /newserv/system volume in sync with the defaults shipped in the
# image, without ever touching files the user has changed.
#
# A file in the volume is considered "unmodified" when its content matches a
# version of that same path shipped by some image (current or previous). The
# known versions are the union of:
#   - /newserv/defaults-history.sha256 (shipped with the image; seeded with the
#     defaults of every previously published image)
#   - $SYSTEM/.defaults-history.sha256 (accumulated in the volume, updated on
#     every start with the current image's defaults)
#
# For each file shipped in the image:
#   - missing from the volume           -> copied
#   - identical to the shipped version  -> nothing to do
#   - matches a known shipped version   -> updated (upstream changed it)
#   - anything else                     -> kept, with a warning (local edit)
# For each file shipped by a previous image but not by this one (removed or
# renamed upstream, e.g. an old patch file):
#   - matches a known shipped version   -> removed
#   - anything else                     -> kept, with a warning
#
# config.json, players/, teams/, licenses/ and the patch directories'
# .metadata-cache.json (regenerated by newserv itself) are never touched.

set -eu

DEFAULTS=/newserv/system-defaults
SYSTEM=/newserv/system
IMAGE_HISTORY=/newserv/defaults-history.sha256
VOLUME_HISTORY="$SYSTEM/.defaults-history.sha256"
PROTECTED='^[0-9a-f]{64}  \./(config\.json$|players/|teams/|licenses/|patch-(bb|pc)/\.metadata-cache\.json$)'

hash_tree() {
  (cd "$1" && find . -type f -print0 | xargs -0 -r sha256sum) | grep -Ev "$PROTECTED" || true
}

# Missing files, directories and symlinks first. Never overwrites.
echo "Syncing missing defaults from $DEFAULTS/ into $SYSTEM/..."
cp -r --update=none "$DEFAULTS"/. "$SYSTEM"/

tmp=$(mktemp -d)

hash_tree "$DEFAULTS" >"$tmp/current"
cat "$IMAGE_HISTORY" "$VOLUME_HISTORY" "$tmp/current" 2>/dev/null | grep -Ev "$PROTECTED" | LC_ALL=C sort -u >"$tmp/history"

# Hash what the volume currently holds, for every path we know about.
cut -c67- "$tmp/history" | LC_ALL=C sort -u | (
  cd "$SYSTEM"
  while IFS= read -r path; do
    [ -f "$path" ] && [ ! -L "$path" ] && printf '%s\0' "$path"
  done | xargs -0 -r sha256sum
) >"$tmp/volume"

awk '
  FILENAME == ARGV[1] { known[substr($0, 67), $1] = 1; next }
  FILENAME == ARGV[2] { shipped[substr($0, 67)] = $1; next }
  {
    path = substr($0, 67)
    if (path in shipped) {
      if ($1 == shipped[path]) next
      print ((path, $1) in known ? "update" : "keep") "\t" path
    } else {
      print ((path, $1) in known ? "remove" : "orphan") "\t" path
    }
  }
' "$tmp/history" "$tmp/current" "$tmp/volume" >"$tmp/actions"

updated=0 removed=0
while IFS=$'\t' read -r action path; do
  case "$action" in
    update)
      cp -a "$DEFAULTS/$path" "$SYSTEM/$path"
      echo "  updated: ${path#./}"
      updated=$((updated + 1))
      ;;
    remove)
      rm -f "$SYSTEM/$path"
      echo "  removed (no longer shipped): ${path#./}"
      removed=$((removed + 1))
      ;;
    keep)
      echo "  WARNING: kept locally modified file; the image ships a different version: ${path#./}"
      ;;
    orphan)
      echo "  WARNING: kept locally modified file that is no longer shipped: ${path#./}"
      ;;
  esac
done <"$tmp/actions"
echo "Defaults sync done: $updated updated, $removed removed."

# newserv refuses to start if two client functions share a file name anywhere
# under client-functions/ (e.g. a locally modified patch that upstream has
# since moved to another directory). Disable the copies the image doesn't ship.
(cd "$SYSTEM" && find ./client-functions -type f \( -name '*.s' -o -name '*.bin' \)) |
  awk -F/ '{ n[$NF]++; p[NR] = $0; b[NR] = $NF } END { for (i = 1; i <= NR; i++) if (n[b[i]] > 1) print p[i] }' |
  while IFS= read -r path; do
    if ! grep -qxF "$path" <(cut -c67- "$tmp/current"); then
      mv "$SYSTEM/$path" "$SYSTEM/$path.disabled"
      echo "  WARNING: disabled ${path#./} (another file with the same name is shipped); renamed to ${path#./}.disabled"
    fi
  done

cp "$tmp/history" "$VOLUME_HISTORY"
rm -rf "$tmp"

exec "$@"
